// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPIDay1.Models;

public partial class Course
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string Crs_name { get; set; }

    [StringLength(50)]
    public string Crs_des { get; set; }

    public int? Duration { get; set; }

    public int? Top_Id { get; set; }

    [ForeignKey("Top_Id")]
    [InverseProperty("Courses")]
    public virtual Topic Top { get; set; }
}